services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "School-ui"
    ports:
      - "4200:80"  # Maps port 4200 to 80 in the container, which is the default port for serving Angular
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app  # Optional: Mounts the current directory to the container's app directory
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
