name: Build and Deploy Angular to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.9.0


      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build -- --configuration production

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your bucket's region


      - name: Sync Build Artifacts to S3
        run: |
          ls -la
          aws s3 sync ./dist/angular-ui-app s3://schoolui20241226134101862700000001 \
            --acl public-read \
            --delete
